# -*- coding: utf-8 -*-
"""método de Interação de ponto fixo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsBkEXbqPGfn20UAAw-9J0LnxUKzCpW4
"""

import numpy as np
import matplotlib.pyplot as plt

# a) f(x) = 2ln(3-cos(x)) - 3x^x + 5sen(x)
# def f(x): return 2*np.log(3 - np.cos(x)) - 3*(x**x) + 5*np.sin(x)
# def g(x): return ( (2*np.log(3 - np.cos(x)) + 5*np.sin(x)) / 3 )**(1/x)
# titulo = "Item (a)"

# b) f(x) = x^2 - 10ln(x) - 5
# def f(x): return x**2 - 10*np.log(x) - 5
# def g(x): return np.sqrt(10*np.log(x) + 5)
# titulo = "Item (b): f(x) = x^2 - 10ln(x) - 5"

# c) f(x) = x^3 - e^(2x) + 3
# def f(x): return x**3 - np.exp(2*x) + 3
# def g(x): return np.log(x**3 + 3) / 2
# titulo = "Item (c)"

# d) f(x) = x + log(x)
# def f(x): return x + np.log10(x)
# def g(x): return 10**(-x)
# titulo = "Item (d)"

# e) f(x) = 2x^3 + x^2 - 2
# def f(x): return 2*x**3 + x**2 - 2
# def g(x): return np.sqrt(2 / (2*x + 1))
# titulo = "Item (e)"

# f) f(x) = sen(x) - ln(x)
# def f(x): return np.sin(x) - np.log(x)
# def g(x): return np.exp(np.sin(x))
# titulo = "Item (f)"

# g) f(x) = e^cos(x) + x^3 - 3
def f(x): return np.exp(np.cos(x)) + x**3 - 3
def g(x): return np.cbrt(3 - np.exp(np.cos(x)))
titulo = "Item (g)"

def ponto_fixo(x0, TOL, itermax):
    i = 1
    xk = x0

    try:
        val_f = f(xk)
    except:
        print("Erro de domínio no chute inicial.")
        return None

    print("\n" * 2)
    print("*" * 80)
    print(f"Método do Ponto Fixo - {titulo}")
    print("*" * 80)
    print(f"{'i':>3} {'xk':>12} {'f(xk)':>12} {'g(xk)':>12} {'ERRO':>12}")
    print("*" * 80)

    print(f"{1:3d} {xk:12.6f} {f(xk):12.6f} {g(xk):12.6f} {'---':>12}")

    ERRO = 1000

    while ERRO >= TOL and i < itermax:
        xk_old = xk

        try:
            xk = g(xk_old)
            i += 1
            ERRO = abs(xk - xk_old)
            print(f"{i:3d} {xk:12.6f} {f(xk):12.6f} {g(xk):12.6f} {ERRO:12.6f}")
        except Exception as e:
            print(f"Erro matemático durante a iteração: {e}")
            break

    return [xk, ERRO, i]

x0 = float(input("Digite o chute inicial (x0): "))
TOL = 0.001
itermax = 40

x_plot = np.linspace(0.1, 4, 400)
plt.plot(x_plot, f(x_plot), label='f(x)')
plt.axhline(0, color='black', linewidth=0.8)
plt.title(f"Gráfico de f(x) - {titulo}")
plt.grid(True)
plt.show()

res = ponto_fixo(x0, TOL, itermax)

if res is not None:
    print("*" * 80)
    print("Resultados Finais:")
    print(f"Valor da Raiz: {res[0]:.6f}")
    print(f"Erro Final: {res[1]:.6f}")
    print(f"Número de Iterações: {res[2]}")
    print(f"f(raiz) = {f(res[0]):.6f}")